### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by talantbekov123** [Abuzakukuruza/Abuzakukuruza.github.io#1]
Нет проблем с валидацией номеров и доменных имен, хорошая работа!

К сожалению текущая реализация содержит ряд недостатков, не позволяющих мне засчитать работу на данной итерации:

**Надо исправить**
Имя:
Нужно исправить: Не проходят валидацию корректные двойные имена Денис-Иван
После исправления проверьте следующие кейсы:
```
Позитивные:
Денис
Денис-Иван
Негативные:
Денис- (дефис, нет двойного имени, допустимо либо Денис, либо Денис-Иван)
Денис-ловеркейс (второе имя должно быть с заглавной буквы)
денис-Ян (первое имя должно быть с заглавной буквы)
Денис-Иvан (имя состоит только из кирилицы)
```
Email:
Нужно исправить: Проходят валидацию не корректные адреса доп символами
Пример: `den~test@gmail.com`, `den!s@gmail.com`

**Можно лучше:**
- файлы logo.svg и cover.jpg, расположенные в репозитории не используются на странице (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить.
- Добавьте .gitignore, содержащий правила, исключающие попадание временных и\или системных файлов в репозиторий.

**Comment by Abuzakukuruza** [comment]
- Валидация формы "Имя" исправлена 

- Валидация формы "Email" исправлена 

- Файлы logo.svg и cover.jpg удалены

- Добавлен файл .gitignore

**Comment by talantbekov123** [comment]
Прошу проверить валидацию поля email, после исправлений смогу пропустить работу.

**Нужно исправить:** Проходят валидацию не корректные адреса доп символами
Пример: den~test@gmail.com, den!s@gmail.com

**Comment by Abuzakukuruza** [comment]
Не знаю в чем проблема, но у меня такие варианты валидации не проходят

![Снимок экрана 2020-03-29 в 2 25 53](https://user-images.githubusercontent.com/60809113/77833082-c42a5b80-7164-11ea-8b95-fd9e4b99898a.png)
![Снимок экрана 2020-03-29 в 2 26 10](https://user-images.githubusercontent.com/60809113/77833083-c7254c00-7164-11ea-9456-2b64d48ab34e.png)

**Comment by talantbekov123** [comment]
Извиняюсь, пропускаю работу! Моя ошибка при проверке.

**Отличная работа!**

**Comment by Abuzakukuruza** [comment]
Хорошо, спасибо большое!
